// src/utils/generatePDF.js
import jsPDF from 'jspdf';

export const generatePDF = (results) => {
    const doc = new jsPDF();
    const { user_name, total_schemes, total_annual_benefit, schemes } = results;

    // Header
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.text('HaqDar', 20, 20);
    doc.setFontSize(10);
    doc.text('har haq milna chahiye', 20, 28);
    doc.text('Your Government Benefits Report', 20, 35);

    // User Info
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(16);
    doc.text(`${user_name}`, 20, 55);

    doc.setFontSize(12);
    doc.setTextColor(71, 85, 105);
    doc.text(`Total Schemes: ${total_schemes}`, 20, 64);
    doc.text(`Total Annual Benefit: Rs. ${total_annual_benefit.toLocaleString('en-IN')}`, 20, 72);

    // Line
    doc.setDrawColor(226, 232, 240);
    doc.line(20, 78, 190, 78);

    // Schemes
    let y = 88;
    schemes.forEach((scheme, i) => {
        if (y > 260) {
            doc.addPage();
            y = 20;
        }

        // Scheme number circle
        doc.setFillColor(234, 88, 12);
        doc.circle(25, y - 2, 4, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.text(`${i + 1}`, 23.5, y);

        // Scheme name
        doc.setTextColor(15, 23, 42);
        doc.setFontSize(12);
        doc.text(scheme.name, 35, y);

        // Benefit
        doc.setTextColor(71, 85, 105);
        doc.setFontSize(10);
        doc.text(`Benefit: Rs. ${scheme.annual_benefit_value.toLocaleString('en-IN')}/year`, 35, y + 7);

        // Apply at
        doc.text(`Apply at: ${scheme.apply_at}`, 35, y + 14);

        // Documents
        if (scheme.documents && scheme.documents.length > 0) {
            doc.setFontSize(9);
            doc.setTextColor(148, 163, 184);
            doc.text(`Documents: ${scheme.documents.join(', ')}`, 35, y + 21);
        }

        y += 32;
    });

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(
            `Generated by HaqDar | haqdar-khaki.vercel.app | Page ${i}/${pageCount}`,
            20, 290
        );
    }

    doc.save(`HaqDar-${user_name.replace(/\s+/g, '-')}.pdf`);
};